### PR TITLE
Switch exercises order

### PR DESCRIPTION
**Pull request by lpalma**
The students already know how to implement functions, so IMO it makes sense to have the first part being _implementing function for existing tests_, since the tests are there and they are correct.

The second part would be **writing tests** because they contain buggy code. It is a more complex step because it involves writing tests and fixing broken code.

I would also like to make a few changes in upcoming PRs, mostly:
* Including more tests in **passing-tests** so students are forced to get the correct implementation
* Explicitly ask for more than one test in **writing-tests** so students will spot bugs by themselves

_PS: this changes are meant for future classes since Class 5 is already following the current structure_

### CODE REVIEW

**Comment by lpalma** [comment]
@40thieves is this gtm?

**Comment by 40thieves** [comment]
In terms of merging - I think we're going to have to deal with merge conflicts with my PR

**Comment by lpalma** [comment]
@40thieves your previous PR has been merged already. I resolved the conflicts with this one

**Comment by 40thieves** [comment]
Oh so it has 🤦‍♂️Thanks!

**Pull request merged**
